spring:
  datasource:
    url: jdbc:postgresql://junction.proxy.rlwy.net:47309/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validade